language: ruby
script: "bundle exec rake spec:coverage"
cache: bundler
before_install:
  - "gem update --system"
after_script:
  - "CODECLIMATE_REPO_TOKEN=<token> bundle exec codeclimate-test-reporter"
rvm:
  - 2.5.0
  - 2.4.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
branches:
  only:
    - master
